# Generated by Django 5.0.3 on 2024-07-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindscape_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
